version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.frontend
    ports:
      - "4200:4200"
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: server/Dockerfile.server
    ports:
      - "5000:5000"
